### PR TITLE
ToC on HTMLGen side

### PR DESCRIPTION
**Pull request by ThunderMikey**
Getting ready on HTMLGen side

### CODE REVIEW

**Comment by Qieerb** [comment]
Toc doesn’t have to be at the beginning and has only one copy of a certain depth, but just wherever the token(s) is/are. So I don’t know if adding it as an option would work.

**Comment by ThunderMikey** [comment]
@Qieerb Do you mean Toc doesn't have to be at the beginning of the HTML document?

Making it as an option is temporary. I'll make it no an option later.

**Comment by Qieerb** [comment]
@ThunderMikey 
no, because Toc is a parsedObj it should be just another item to parse.
if the parser sees a TOC token while it is parsing, it should build a toc parseObj there.
and HTMLGen will just see it as any other parsedObj and make it into html

**Comment by ps-george** [comment]
1. See TOC Token (and any options afterwards: depth, excludes)
2. Take header list (already got it), apply options. (List.filter according to options. Remove headers deeper than depth if  depth is specified)
3. List.map over header list, and transform each HeaderName into a hyperlink to its id.
4. Create Ttoc ParsedObj containing this list of headers.
5. HTMLGen for Ttoc was already done

Note: Ttoc doesn't need max_depth anymore, so could remove this from the type.

**Comment by ps-george** [comment]
(since depth is dealt with in the Parser filtering the list of headers)

**Comment by ps-george** [comment]
Something like that; option parsing needs to be added in. Doesn't work in VSCode, but the html is correct.

**Comment by ThunderMikey** [comment]
@Qieerb For this test, a line with reference at the beginning disappears.

```fsharp
Paragraph
     [[FrmtedString (Literal "text5"); Reference (Literal "(Wang, 2017)","Eric");
       FrmtedString (Literal "text6")]];

// but expected to be

Paragraph
     [[Reference (Literal "1","1"); FrmtedString (Literal ",footer1")];
      [FrmtedString (Literal "text5"); Reference (Literal "(Wang, 2017)","Eric");
       FrmtedString (Literal "text6")]];
```

**Comment by ThunderMikey** [comment]
@ps-george I was gonna uncomment a test in FMarkCLI.

**Pull request merged**
