### PR TITLE
revert back skip decision

### PR DESCRIPTION
**Pull request by ThunderMikey**

### CODE REVIEW

**Comment by ps-george** [comment]
Causes an error when skip=1

**Comment by ThunderMikey** [comment]
@ps-george Error in which module test?

**Comment by ps-george** [comment]
Must've been my previous test with a double indent.

**Comment by ThunderMikey** [comment]
It now has passed all tests, apparently.

**Comment by ps-george** [comment]
I'm not home, I'll put the test case back in when I get back.

**Comment by ps-george** [comment]
Actually @ThunderMikey  look at the travis logs. https://travis-ci.org/ymherklotz/FMark/builds/353805754?utm_source=github_status&utm_medium=notification

It already fails at line 953.
Error in build.sh not telling Travis that it has failed. I will fix that.

**Comment by ps-george** [comment]
image

Still failing. Non-elegant version in htmlgen passes all tests; leave this and work on TOC 💯

**Comment by ThunderMikey** [comment]
@ps-george I'm working on this.

**Pull request merged**
